### ISSUE TITLE
夜间模式样式

### ISSUE THREAD

**Issue by shi-an** [Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg#15]
![image](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/assets/79352488/f615dd83-bbc0-4ef1-a9f7-41bd8ba82d8a)
![image](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/assets/79352488/0a056062-70d5-45f5-9489-4c6179e02aa1)

**Comment by zhulinyv** [comment]
同样的问题，mark 一下

**Comment by Night-stars-1** [comment]
鼠标悬浮消息1秒翻译，需要配置id和key

**Comment by shi-an** [comment]
> 鼠标悬浮消息1秒翻译，需要配置id和key

能不能加个百度的

**Comment by Night-stars-1** [comment]
> > 鼠标悬浮消息1秒翻译，需要配置id和key
> 
> 能不能加个百度的

之后有时间加

**Comment by Night-stars-1** [comment]
> > 鼠标悬浮消息1秒翻译，需要配置id和key
> 
> 能不能加个百度的

已添加
