### ISSUE TITLE
+1 按钮过大

### ISSUE THREAD

**Issue by lgc2333** [Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg#19]
![image](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/assets/59048777/9ccc016c-f09d-462e-ba82-9bc2e941f8af)

插件列表
![image](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/assets/59048777/83c6ed7b-5e2e-49e2-a6c0-d2a1666dfdeb)
![image](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/assets/59048777/150f69ff-5211-42c8-a056-45a3674db959)
![image](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/assets/59048777/b0e141f2-3ff7-4222-a436-9ff328ad3e09)

系统
![image](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/assets/59048777/acef740c-6dbd-4fb9-8ed7-c1fc8ce51223)

**Comment by lgc2333** [comment]
版本信息

![image](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/assets/59048777/eb639822-9be3-4954-8a6c-92424e867d1d)

**Comment by Night-stars-1** [comment]
最新版尝试修复了一下，不知道有没有用

**Comment by lgc2333** [comment]
修好了，感谢
