### ISSUE TITLE
时间显示被截断

### ISSUE THREAD

**Issue by UshioA** [Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg#21]
开启消息时间显示, 在回复一个消息时, 源消息过长会导致回复的文本和时间显示不全, 被截断. 截断的程度和窗口宽度有关. 
![图片](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/assets/79308995/9b04ab03-4992-40e8-ac58-5084c2a92e7c)
![图片](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/assets/79308995/7e983010-aa85-475f-8f5e-a4a19ae1d242)
版本: 
![图片](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/assets/79308995/b94f8809-c324-4942-b879-8b4d27e87c6f)
仅开启`QQ增强`一个插件.

**Comment by Night-stars-1** [comment]
修复了
