### ISSUE TITLE
插件不会自动生成 sidebar_list 键

### ISSUE THREAD

**Issue by TomyJan** [Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg#25]
当 `settings.json` 文件中不存在 `sidebar_list` 键时, 插件不会生成相应 array 反而会隐藏所有支持的侧边栏按钮

另外, 是否可以支持隐藏新版本新添加的 `管理侧边栏` 按钮, 强迫症很难受, 以及是否可以隐藏下方的 `邮箱` `文件` `收藏` 这几个按钮?

**Comment by Night-stars-1** [comment]
该侧边栏管理是基于ipc的，下方的文件不能隐藏，只能隐藏云控的东西，后面会更新其他位置的隐藏

**Comment by Night-stars-1** [comment]
已更新
