### ISSUE TITLE
QQ增强的GPT功能怎么使用

### ISSUE THREAD

**Issue by theunknownpeople1** [Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg#26]
QQ增强的GPT功能怎么使用，输入了api以后右键消息使用gpt没有反应，聊天界面不能滚动

**Comment by Night-stars-1** [comment]
https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/commit/b077e454e717fc11ffc5437574cf891913389d65
