### ISSUE TITLE
点击二维码识别的链接无法关闭窗口

### ISSUE THREAD

**Issue by shi-an** [Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg#30]
![unknown_2023 08 31-22 19](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/assets/79352488/8797ddef-2a53-4922-becc-e638de05bdab)

**Comment by Night-stars-1** [comment]
已经去掉点击按钮了
