### ISSUE TITLE
求群聊显示备注/qq昵称功能

### ISSUE THREAD

**Issue by Huanting93** [Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg#31]
求一个群聊消息列表中昵称显示类似以下

【头衔】群名片<备注/qq昵称>

旧版ntr的功能
![image](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/assets/36955112/00552bf1-a0b1-4c5d-bf5b-ecb2fee49671)

**Comment by Night-stars-1** [comment]
# 4bc1c1293c6da54e8fd1a0704ef8ddb51209f534
