### ISSUE TITLE
建议更改时间显示的位置

### ISSUE THREAD

**Issue by MC-cookies** [Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg#32]
个人认为现在**时间显示**的位置不是很好
建议将时间放在消息的左右侧而不是直接并到消息中
:)

**Comment by MC-cookies** [comment]
比如discord的时间显示
![image](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/assets/117754398/ee02ee50-cb49-4bc8-959b-33d1876758fb)

**Comment by Night-stars-1** [comment]
# 4bc1c1293c6da54e8fd1a0704ef8ddb51209f534
