### ISSUE TITLE
在名称后显示时间时无分隔

### ISSUE THREAD

**Issue by MC-cookies** [Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg#33]
如题

**Comment by MC-cookies** [comment]
添加一个空格会看起来好很多

**Comment by MC-cookies** [comment]
![image](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/assets/117754398/60c76712-205c-4a37-a7d2-abeedf8b9a78)

**Comment by MC-cookies** [comment]
另外,希望适配在名称后显示时间时自定义颜色 :)

**Comment by Night-stars-1** [comment]
# 439c8f3
