### ISSUE TITLE
链接预览出现问题

### ISSUE THREAD

**Issue by HeimNad** [Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg#35]
系统: MacOS 14.1
LLQQNT信息:
<img width="610" alt="image" src="https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/assets/107762511/7ea9ef30-b61a-4d72-a27c-ffd28f4f0ab8">
QQ版本: 6.9.19-16183 AppStore版

---

问题: 吾爱破解论坛解析出现乱码
<img width="1073" alt="image" src="https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/assets/107762511/65471ed9-0b77-4aa1-b8a7-7ac156b7f772">

**Comment by Night-stars-1** [comment]
第三方插件的原因目前无法修复
