### ISSUE TITLE
消息时间遮挡住重发消息的感叹号

### ISSUE THREAD

**Issue by shi-an** [Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg#36]
![{6CE6C915-D2FD-48dd-84B3-7C7B336A05CB}](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/assets/79352488/6a3051e8-40eb-4a1a-8ada-d73d2f3dad1b)
![{08B8A814-F3B9-4967-8F98-FD91E7CA1758}](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/assets/79352488/1bce9cf3-53e2-444f-88e6-58953afaa03a)

**Comment by Night-stars-1** [comment]
这不是我的插件干的
