### ISSUE TITLE
+1

### ISSUE THREAD

**Issue by shi-an** [Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg#7]
回复文字不能+1  回复图片可以+1
![image](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/assets/79352488/4eb19897-5ae5-49af-8e3a-e6ed4c93b9a8)
![image](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/assets/79352488/1ccacddf-d21d-4033-bb2e-ec8fe137b7d4)

**Comment by Night-stars-1** [comment]
https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/releases/tag/v1.0.4
