### ISSUE TITLE
插件冲突

### ISSUE THREAD

**Issue by shi-an** [Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg#8]
启用markdown后   文字消息没有+1
![image](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/assets/79352488/00dccdf1-1d9c-4c71-a308-0612e4cc1b95)
![image](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/assets/79352488/74453956-1fdb-4147-bf9d-7031423419b8)

**Comment by Night-stars-1** [comment]
他的插件对此继续了更改
